### ISSUE TITLE
帧率解锁的Slider的提示颜色错误

### ISSUE THREAD

**Issue by ZhiJuan0724** [BoxCatTeam/SRCat#10]
这个字完全看不清
![image](https://github.com/BoxCatTeam/SRCat/assets/36944634/e4bf845c-980a-483a-81e9-fc506466f7cb)

而且我的建议是直接输入 用滑动没必要

**Comment by ZhiJuan0724** [comment]
好像不是背景的问题 是字体颜色的问题
不过好像没能调字体颜色
我觉得背景无论主题都黑算了

**Comment by bakaomg** [comment]
已知问题，亮色下背景颜色与文字颜色设置出错
改成输入也行，下版本改
