### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by MythicalPalace** [BoxCatTeam/SRCat#15]
始终出现：“
提示
跃迁数据刷新失败，可能是链接已失效，请尝试进入游戏内重新获取。
”问题
重新打开跃迁记录界面也无法解决该问题

**Comment by bakaomg** [comment]
1. 确保点击并进入了 `查看详细` 页面
![image](https://github.com/BoxCatTeam/SRCat/assets/40896676/087fbc38-0066-4e1c-8667-99b767d2dde7)

2. 检查 `SRCat` 所在目录是否有读写权限，例如 `data` 目录下是否存在 `hsr_data_temp`，如果有请删除重新尝试是否能获取，如果没有请检查是否有充足的权限
![image](https://github.com/BoxCatTeam/SRCat/assets/40896676/bc711d5e-41de-43d9-b255-1144b478602f)

**Comment by bakaomg** [comment]
fix: [69359e4](https://github.com/BoxCatTeam/SRCat/commit/69359e441f28ea1e7f59d96b7144b35a87c00baa)
