### ISSUE TITLE
保底提示疑问

### ISSUE THREAD

**Issue by AkagiYui** [BoxCatTeam/SRCat#17]
请问“保底”文字的提示是什么意思，景元这里应该显示”保底“吗？
![image](https://github.com/BoxCatTeam/SRCat/assets/39934721/6a2aee4e-c692-4872-bdab-ee3117f72293)

查看 commit 似乎已经修复。

**Comment by bakaomg** [comment]
master 分支中已修复，但并未发版

**Comment by AkagiYui** [comment]
已了解。
