### ISSUE TITLE
跃迁希望可以显示已垫抽数

### ISSUE THREAD

**Issue by imingz** [BoxCatTeam/SRCat#26]
类似下面这种
![image](https://github.com/BoxCatTeam/SRCat/assets/57054141/f998e1a3-ce6b-422e-acc3-8cceb31988b9)

**Comment by bakaomg** [comment]
有显示已垫抽数的其实，在中间一列

**Comment by imingz** [comment]
> 有显示已垫抽数的其实，在中间一列

好的，谢谢
