### ISSUE TITLE
你好，流光定影（光锥池）里卡夫卡的光锥<只需等待>不显示，在lightcone.json也没有

### ISSUE THREAD

**Issue by hualixiaojiaoqi** [BoxCatTeam/SRCat#31]
![image](https://github.com/BoxCatTeam/SRCat/assets/148187411/9d780206-644a-45d5-a719-e922dc300e7e)
![image](https://github.com/BoxCatTeam/SRCat/assets/148187411/853470b5-368c-442a-9b67-08c21124590b)

**Comment by bakaomg** [comment]
~~应该是元数据处理脚本出问题，导致漏了~~
等 1.4 下半池子更新的时候再一并更新（

**Comment by Dongagent** [comment]
辛苦大佬了，抽到托帕了！坐等更新~

**Comment by bakaomg** [comment]
> 辛苦大佬了，抽到托帕了！坐等更新~

好耶，恭喜~

**Comment by bakaomg** [comment]
已经更新元数据了，双卡池我也不是很确定会不会出问题（
