### ISSUE TITLE
[Bug]元数据缺失

### ISSUE THREAD

**Issue by DrMythical** [BoxCatTeam/SRCat#35]
<img width="894" alt="{0AA3EF14-1BCB-4e82-906F-505B2E6F457D}" src="https://github.com/BoxCatTeam/SRCat/assets/104907432/56e4c920-5e48-44a7-a2e9-ed241145c489">
<img width="894" alt="{AD554C35-B327-4482-82F4-E0F37202C45F}" src="https://github.com/BoxCatTeam/SRCat/assets/104907432/65bf8a09-3305-4219-b2bf-ee2a1a419950">
ps：因为我没抽阮梅的专属光锥，所以看不到《镜中故我》的图标是否缺失

**Comment by bakaomg** [comment]
已更新元数据，重启软件等待更新下载即可
