### ISSUE TITLE
[BUG] 抽卡记录异常重复

### ISSUE THREAD

**Issue by Welkin-Totoro** [BoxCatTeam/SRCat#6]
### 使用环境
版本：[0.0.1-100005](https://github.com/BoxCatTeam/SRCat/releases/tag/100005)
系统：Win10

### 错误表现
群星跃迁中出现了三个五星角色和三个五星光锥
![image](https://github.com/BoxCatTeam/SRCat/assets/21326609/1ce7ca9a-384a-4b16-afef-4e08dfacc2a2)

### 实际期望
群星跃迁中应为一个五星角色和一个五星光锥
|||
|:-|-:|
|白露|9|
|时节不居|82|

**Comment by bakaomg** [comment]
将 SRCat根目录\data\database\warp.db 文件发送至 support@boxcat.org

**Comment by Welkin-Totoro** [comment]
> 请将 SRCat根目录\data\database\warp.db 文件发送至 [support@boxcat.org](mailto:support@boxcat.org)

已发送

**Comment by bakaomg** [comment]
经过调查，是判断抽卡记录是否存在部分传入了错误类型，导致有多条重复的记录，因而计算出错。

目前数据请再确认下是否正确，待会我发个新版
![image](https://github.com/BoxCatTeam/SRCat/assets/40896676/b36d709e-e2bd-45af-b4e9-d27b3d21c210)

**Comment by Welkin-Totoro** [comment]
以上统计数据中【总抽数】，【五星数】及【各个五星消耗抽数】均正确，应该没错了
三星四星数就不挨个验证了

**Comment by bakaomg** [comment]
已在 [releases](https://github.com/BoxCatTeam/SRCat/releases/tag/100006) 发布新版，可以再次尝试下是否正常

**Comment by Welkin-Totoro** [comment]
已验证，覆盖安装100006版本后数据显示正确
