### ISSUE TITLE
启动游戏界面灰屏

### ISSUE THREAD

**Issue by 1376367262** [BoxCatTeam/SRCat#9]
![image](https://github.com/BoxCatTeam/SRCat/assets/16742151/712a6aa7-4fea-43c7-9cfd-470dab8ec461)

**Comment by 1376367262** [comment]
游戏路径设置正确

**Comment by bakaomg** [comment]
请提供系统版本

**Comment by 1376367262** [comment]
> 请提供系统版本 以及可以尝试使用官方启动器启动一次游戏后，随意更改下显示设置再重启 SRCat 查看是否正常

版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎10/‎1
操作系统版本	22621.1778
体验	Windows Feature Experience Pack 1000.22642.1000.0

**Comment by bakaomg** [comment]
排查出问题所在位置了，下版本修复

**Comment by 1376367262** [comment]
> 排查出问题所在位置了，下版本修复

谢谢大佬OVO
